# put this in .forgejo/workflows, and edit the cronjob to be the right time esired

on:
  schedule:
    - cron: '* * * * *' # minute
    # - cron: '0 * * * *' # every hour
    # - cron: '*/15 * * * *' # every 15mins
    # - cron: '0 2 * * *' # every day @ 2am
    # - cron: '0 2 * * 1' # every monday @ 2am
  workflow_dispatch:

jobs:
  sync:
    uses: e-shrdlu/workflows/.forgejo/workflows/pull-remote-mirrors-on-timer.yml@main
    secrets: inherit
