on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync from github
        run: |
          git clone --mirror https://oauth2:${{ secrets.GITHUB_TOKEN }}@git.lan.everyls.net/e-shrdlu/${{ inputs.repo_name }}.git repo
          cd repo
          git fetch https://x-access-token:${{ secrets.GH_PAT }}@github.com/e-shrdlu/${{ inputs.repo_name }}.git '+refs/heads/*:refs/heads/*' '+refs/tags/*:refs/tags/*'
          git push --mirror https://oauth2:${{ secrets.GITHUB_TOKEN }}@git.lan.everyls.net/e-shrdlu/${{ inputs.repo_name }}.git
